const CollectionAnuncio = {
	"nome":"",
	"email":"",
	"telefone":"",
	"cpf":"",
	"profissao":"",
	"endereco":"",
	"cidade":"",
	"microrregiao":"",
	"uf":"",
	"preco":"",
	"anuncio":"",
	"certificados":"",
	"cartao_visita":"",
	"foto":"",
	"observacoes":"",
	"user_uid":"",
	"data_nascimento":"",
	"observacoes":"",
	"avaliacao":"",
	"termo_acordo":"",
	"provider_id":"",
};

export default CollectionAnuncio;